# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "k8s-master" do |master|
    master.vm.box = "debian/buster64"
    master.vm.network "private_network", ip: "192.168.56.6"
    master.vm.hostname = "k8s-master"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
    master.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y docker.io
      systemctl start docker
      systemctl enable docker
      # Installation et configuration de Kubernetes
      # ...
      # Installation de Webmin
      wget http://prdownloads.sourceforge.net/webadmin/webmin_1.941_all.deb
      dpkg --install webmin_1.941_all.deb
      apt-get install -f
      systemctl enable webmin
    SHELL
  end
end
