# Utiliser l'image officielle MySQL
FROM mysql:5.7

# Définir les variables d'environnement pour MySQL
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword

# Exposer le port de la base de données
EXPOSE 3306
