# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  (1..2).each do |i|
    config.vm.define "db-server-#{i}" do |db|
      db.vm.box = "debian/buster64"
      db.vm.network "private_network", ip: "192.168.56.#{3+i}"
      db.vm.hostname = "db-server-#{i}"
      db.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
      end
      db.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y docker.io
        systemctl start docker
        systemctl enable docker
      SHELL
      db.vm.provision "docker" do |d|
        d.build_image "/path/to/db/dockerfile/folder", args: "-t mydbimage"
        d.run "mydbimage", args: "-d -p 3306:3306 --name mydbcontainer"
      end
      # Installation de Webmin
      db.vm.provision "shell", inline: <<-SHELL
        wget http://prdownloads.sourceforge.net/webadmin/webmin_1.941_all.deb
        dpkg --install webmin_1.941_all.deb
        apt-get install -f
        systemctl enable webmin
      SHELL
    end
  end
end
